export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_SUCESS = "GET_BOOKS_SUCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";

export const GET_BOOKS_DETAILS_REQUEST = "GET_BOOKS_DETAILS_REQUEST";
export const GET_BOOKS_DETAILS_SUCESS = "GET_BOOKS_DETAILS_SUCESS";
export const GET_BOOKS_DETAILS_FAIL = "GET_BOOKS_DETAILS_FAIL";
export const GET_BOOKS_DETAILS_RESET = "GET_BOOKS_DETAILS_RESET";
